unsigned int H1(char * str);
unsigned int H2(char * str);
unsigned int H3(char * str);
unsigned int H4(char * str);
unsigned int H5(char * str);
int HashTableConstract(HashTable * elem);
int ListConstruct(List * elem);
int AddToTable(HashTable * hash_table, char * str_to_add);
int Print(HashTable * hashTable);
int StRcMp(const char * a, const char * b);
